automation:
  - alias: Notify when new network device has been discovered
    initial_state: true
    trigger:
      - platform: event
        event_type: device_tracker_new_device
    condition:
      condition: template
      value_template: '{{ not trigger.event.data.entity_id | regex_match("device_tracker.10_7_0_[\d]{1,3}_([\w]{2}_){5}([\w]{2})", ignorecase=False) }}'
    action:
      - service: notify.html5
        data_template:
          message: "A new device has been detected: {{ trigger.event }} - ID: {{ trigger.event.data.entity_id }}"
      - service: notify.pushover
        data_template:
          message: "A new device has been detected: {{ trigger.event }}"

  - alias: Notify when new network device has been discovered (BT)
    initial_state: false
    trigger:
      - platform: event
        event_type: device_tracker_new_device
    condition:
      condition: template
      value_template: '{{ trigger.event.data.entity_id | regex_match("device_tracker.10_7_0_[\d]{1,3}_([\w]{2}_){5}([\w]{2})", ignorecase=False) }}'
    action:
      - service: notify.html5
        data_template:
          message: 'New Bluetooth device: {{ trigger.event.data.mac | regex_replace("10.7.0.[\d]{1,3}_","") }}'

# vim: set filetype=yaml et sw=2 ts=2 :
