zoneminder:
  host: !secret zm_hostname
  path: /zm
  ssl: true
  # verify_ssl: true
  username: !secret zm_username
  password: !secret zm_password


# camera:
#   platform: zoneminder


sensor:
  - platform: zoneminder


switch:
  - platform: zoneminder
    command_on: Modect
    command_off: Monitor
