xiaomi_aqara:
  interface: !secret lan_ipv4_addr
  gateways:
    - mac: !secret mi_gw_mac
      key: !secret mi_gw_api_key

remote:
  - platform: xiaomi_miio
    host: !secret miio_ir_hostname
    token: !secret miio_ir_token
    commands:
      ac_toggle:
        command:
          - raw:Z6VHADACAACbBgAAxggAAIERAAAaIwAAOCMAACigAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1AAAAAAAAAAAAEBAQEBAQEAAAEAAAAAAAEBAAEBAQEBBgJAA=
      ac_mode:
        command:
          - raw:Z6VHAC8CAACiBgAA6wgAAKsRAAAOIwAAKKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAAAAAAAAAAEBAQEBAQEAAAAAAAAAAAEBAQEBAQEBBQJAA=
      ac_temp_up:
        command:
          - raw:Z6VHADICAACXBgAAqwgAAIURAAA1IwAAKKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAAAAAAAAAAEBAQEBAQEBAAEAAAAAAAABAAEBAQEBBQJAA=
      ac_temp_down:
        command:
          - raw:Z6VHACgCAABaAgAAqAYAAOsIAACrEQAADiMAACigAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFEAAAEAAAEAAAICAgICAgIAAgIAAAEAAAIAAQICAgICBgNQA=
      ac_fan_speed:
        command:
          - raw:Z6VHAAoCAABaAgAAvwYAAOcIAADCEQAA+SIAACigAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFEBAQEBAQEBAQICAgICAgICAgIBAQEBAQEBAQICAgICBgNQA=
      ac_sleep:
        command:
          - raw:Z6VHACkCAACyBgAA5QgAAKoRAAAPIwAAKKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAAAAAAAAAAEBAQEBAQEBAQAAAAAAAAAAAQEBAQEBBQJAA=
      ac_timer:
        command:
          - raw:Z6VHAA0CAABWAgAAuwYAAO0IAACsEQAADCMAACigAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFEBAQEBAQEBAQICAgICAgICAQEBAQEBAQECAgICAgICBgNQA=


script:
  aqara_add_device:
    sequence:
      service: xiaomi_aqara.add_device
      data:
        gw_mac: !secret mi_gw_mac

  aqara_ring_bell:
    sequence:
      - condition: state
        entity_id: input_boolean.dnd
        state: 'off'
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret mi_gw_mac
          ringtone_id: 10
          ringtone_vol: 100


group:
  fridge:
    name: Fridge
    view: no
    icon: mdi:fridge
    control: hidden
    entities:
      - binary_sensor.door_window_sensor_fridge_door
      - sensor.temperature_fridge
      - sensor.temperature_fridge_crisper
      - sensor.humidity_fridge
      - sensor.humidity_fridge_crisper
      - sensor.pressure_fridge
      - sensor.pressure_fridge_crisper

  terrace_doors:
    name: Terrace Doors
    view: no
    icon: mdi:door
    entities:
      - binary_sensor.door_window_sensor_terrace_door
      - binary_sensor.door_window_sensor_bedroom_terrace_door

  windows:
    name: Windows
    view: no
    icon: mdi:glassdoor
    entities:
      - binary_sensor.door_window_sensor_bedroom_terrace_door
      - binary_sensor.door_window_sensor_front_door
      - binary_sensor.door_window_sensor_terrace_door
      - binary_sensor.door_window_sensor_bedroom_window
      - binary_sensor.door_window_sensor_office_window_large
      - binary_sensor.door_window_sensor_kitchen_window
      - binary_sensor.door_window_sensor_office_window_small
      - binary_sensor.door_window_sensor_living_room_window

  aqara_buttons:
    name: Aqara buttons
    view: no
    icon: mdi:button
    entities:
      - binary_sensor.wall_switch_office_both
      - binary_sensor.bedroom_switch


automation:
  - alias: Turn on the terrace light when door opened during nighttime
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_terrace_door
        to: 'on'
    condition:
      condition: sun
      after: sunset
      before_offset: "-1:00:00"
    action:
      - service: script.smoke_break
      - service: cover.open_cover
        data:
          entity_id: cover.living_room_door

  - alias: Alert when the fridge has been open for 2 min
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_fridge_door
        to: 'on'
        for:
          minutes: 2
    action:
      - service: notify.html5
        data:
          message: "The fridge has been opened for at least 2 minutes"
          data:
            tag: 'fridge-open'

  - alias: Alert when fridge temperature is above 15C
    initial_state: true
    trigger:
      - platform: numeric_state
        entity_id: sensor.temperature_fridge
        above: 15
    action:
      - service: notify.html5
        data_template:
          message: 'The fridge temperature is at {{ trigger.to_state.state }}C!'
          data:
            tag: 'fridge-temp-high'

  - alias: Alert when fridge crisper temperature is above 10C
    initial_state: true
    trigger:
      - platform: numeric_state
        entity_id: sensor.temperature_fridge_crisper
        above: 10
    action:
      - service: notify.html5
        data_template:
          message: 'The fridge crisper temperature is at {{ trigger.to_state.state }}C!'
          data:
            tag: 'fridge-crisper-temp-high'

  - alias: Alert when water leak detected
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.water_leak_sensor_bathroom_sink
          - binary_sensor.water_leak_sensor_bathtub
          - binary_sensor.water_leak_sensor_kitchen_sink
        to: 'on'
    action:
      - service: notify.html5
        data_template:
          message: 'Water leak detected at {{ trigger.to_state.attributes.friendly_name }}!'
          data:
            tag: 'water-leak-{{ trigger.to_state.entity_id }}'

  - alias: React to single button press on office aqara wall switch
    initial_state: true
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_office_left
        click_type: single
    action:
      - service: light.toggle
        entity_id: light.yeelight_office

  - alias: React to single (right) button press on office aqara wall switch
    initial_state: true
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_office_right
        click_type: single
    action:
      - service: light.toggle
        entity_id: light.office

  - alias: React to single (both) button press on office aqara wall switch
    initial_state: true
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_office_both
        click_type: both
    action:
      - service: light.turn_off
        entity_id: light.office, light.yeelight_office
      - service: cover.close_cover
        entity_id: cover.office

  - alias: React to single button press on bedroom aqara wall switch
    initial_state: true
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_bedroom_left
        click_type: single
    action:
      - service: script.bedtime

  - alias: React to single (right) button press on bedroom aqara wall switch
    initial_state: true
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_bedroom_right
        click_type: single
    action:
      # - service: script.all_off
      - service: script.lock_door

  - alias: React to single (both) button press on bedroom aqara wall switch
    initial_state: true
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_bedroom_both
        click_type: both
    action:
      - service: script.all_off
      - service: script.lock_door
      - service: script.arlo_night

  - alias: React to single button press on aqara button
    initial_state: true
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.bedroom_switch
        click_type: single
    action:
      service: script.bedtime

  - alias: React to double button press on aqara button
    initial_state: true
    trigger:
      platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.bedroom_switch
        click_type: double
    action:
      - service: script.all_off
      - service: script.arlo_home

  - alias: Turn on doorpi screen when motion is detected
    initial_state: True
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_front_door
      to: 'on'
    action:
      - service: script.turn_on_doorpi_screen

  - alias: Turn on bathroom light when motion is detected
    initial_state: True
    trigger:
      platform: state
      # entity_id: binary_sensor.bathroom_presence
      entity_id: binary_sensor.bathroom_motion_motion_sensor
      to: 'on'
    action:
      - service: script.turn_on_bathroom_light_switch

  - alias: Cube event flip90
    initial_state: True
    trigger:
      platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.aqara_cube
        action_type: flip90
    action:
      - service: notify.html5
        data:
          message: "FLIP90"
          data:
            tag: "aqara-cube"

  - alias: Cube event flip180
    initial_state: True
    trigger:
      platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.aqara_cube
        action_type: flip180
    action:
      - service: notify.html5
        data:
          message: "FLIP180"
          data:
            tag: "aqara-cube"

  - alias: Cube event move
    initial_state: True
    trigger:
      platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.aqara_cube
        action_type: move
    action:
      - service: notify.html5
        data:
          message: "MOVE"
          data:
            tag: "aqara-cube"

  - alias: Cube event tap_twice
    trigger:
      platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.aqara_cube
        action_type: tap_twice
    action:
      - service: notify.html5
        data:
          message: "TAP_TWICE"
          data:
            tag: "aqara-cube"

  - alias: Cube event shake_air
    trigger:
      platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.aqara_cube
        action_type: shake_air
    action:
      - service: notify.html5
        data:
          message: "SHAKE"
          data:
            tag: "aqara-cube"

  - alias: Cube event rotate
    trigger:
      platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.aqara_cube
        action_type: rotate
    action:
      - service: notify.html5
        data_template:
          message: "Rotate: {{ trigger.event.data.action_value }}"
          data:
            tag: "aqara-cube"


homeassistant:
  customize:
    light.aqara_gateway:
      friendly_name: Aqara Gateway Light
      icon: mdi:bridge
    sensor.aqara_gateway_illumination:
      friendly_name: Aqara Gateway Light Level
    binary_sensor.bedroom_switch:
      friendly_name: "Bedroom switch (small)"
    binary_sensor.door_window_sensor_fridge_door:
      friendly_name: Fridge Door
      device_class: door
    binary_sensor.door_window_sensor_terrace_door:
      friendly_name: Terrace Door
      device_class: door
    binary_sensor.door_window_sensor_kitchen_window:
      friendly_name: Kitchen Window
      device_class: window
    binary_sensor.door_window_sensor_office_window_large:
      friendly_name: "Office Window (large)"
      device_class: window
    binary_sensor.door_window_sensor_office_window_small:
      friendly_name: "Office Window (small)"
      device_class: window
    binary_sensor.door_window_sensor_bedroom_window:
      friendly_name: "Bedroom Window"
      device_class: window
    binary_sensor.door_window_sensor_bedroom_terrace_door:
      friendly_name: "Terrace Door (Bedroom)"
      device_class: door
    binary_sensor.door_window_sensor_bedroom_door:
      friendly_name: "Bedroom Door"
      device_class: door
    binary_sensor.door_window_sensor_front_door:
      friendly_name: "Front Door"
      device_class: door
    binary_sensor.water_leak_sensor_bathroom_sink:
      friendly_name: "Bathroom Sink"
    binary_sensor.water_leak_sensor_kitchen_sink:
      friendly_name: "Kitchen Sink"
    binary_sensor.water_leak_sensor_bathtub:
      friendly_name: "Bathtub"
    binary_sensor.door_window_sensor_living_room_window:
      friendly_name: "Living Room Window"
      device_class: window
    binary_sensor.motion_sensor_front_door:
      friendly_name: "Front door motion sensor"
    binary_sensor.motion_sensor_terrace:
      friendly_name: "Terrace motion sensor"
      # device_class: motion
    sensor.motion_sensor_illumination_terrace:
      friendly_name: "Terrace illumination sensor"
      battery_ignore: true
    binary_sensor.motion_sensor_office:
      friendly_name: "Office motion sensor"
      # device_class: motion
    sensor.motion_sensor_illumination_office:
      friendly_name: "Office illumination sensor"
      battery_ignore: true
    binary_sensor.motion_sensor_living_room:
      friendly_name: "Living Room motion sensor"
      # device_class: motion
    sensor.motion_sensor_illumination_living_room:
      friendly_name: "Living Room illumination sensor"
      battery_ignore: true
    sensor.motion_sensor_illumination_front_door:
      friendly_name: "Front door illumination sensor"
      battery_ignore: true
    binary_sensor.wall_switch_bedroom_left:
      friendly_name: "Bedroom wall switch (L)"
      battery_ignore: true
    binary_sensor.wall_switch_bedroom_right:
      friendly_name: "Bedroom wall switch (R)"
      battery_ignore: true
    binary_sensor.wall_switch_bedroom_both:
      friendly_name: "Bedroom wall switch (L+R)"
      battery_friendly_name: "Bedroom wall switch"
    binary_sensor.wall_switch_office_left:
      friendly_name: "Office wall switch (L)"
      battery_ignore: true
    binary_sensor.wall_switch_office_right:
      friendly_name: "Office wall switch (R)"
      battery_ignore: true
    binary_sensor.wall_switch_office_both:
      friendly_name: "Office wall switch (L+R)"
      battery_friendly_name: "Office wall switch"
    sensor.humidity_fridge:
      friendly_name: Fridge Humidity
      icon: mdi:water-percent
      battery_ignore: true
    sensor.pressure_fridge:
      friendly_name: Fridge Pressure
      icon: mdi:arrow-collapse-all
      battery_ignore: true
    sensor.temperature_fridge:
      friendly_name: Fridge Temperature
    sensor.humidity_fridge_crisper:
      friendly_name: Fridge Crisper Humidity
      icon: mdi:water-percent
      battery_ignore: true
    sensor.pressure_fridge_crisper:
      friendly_name: Fridige Crisper Pressure
      icon: mdi:arrow-collapse-all
      battery_ignore: true
    sensor.temperature_fridge_crisper:
      friendly_name: Fridge Crisper Temperature
    sensor.humidity_terrace:
      friendly_name: Terrace Humidity
      icon: mdi:water-percent
      battery_ignore: true
    sensor.pressure_terrace:
      friendly_name: Terrace Pressure
      icon: mdi:arrow-collapse-all
      battery_ignore: true
    sensor.temperature_terrace:
      friendly_name: Terrace Temperature
    sensor.humidity_bedroom:
      friendly_name: Bedroom Humidity
      icon: mdi:water-percent
      battery_ignore: true
    sensor.pressure_bedroom:
      friendly_name: Bedroom Pressure
      icon: mdi:arrow-collapse-all
      battery_ignore: true
    sensor.temperature_bedroom:
      friendly_name: Bedroom Temperature
    sensor.humidity_living_room:
      friendly_name: Living Room Humidity
      icon: mdi:water-percent
      battery_ignore: true
    sensor.pressure_living_room:
      friendly_name: Living Room Pressure
      icon: mdi:arrow-collapse-all
      battery_ignore: true
    sensor.temperature_living_room:
      friendly_name: Living Room Temperature
    sensor.humidity_office:
      friendly_name: Office Humidity
      icon: mdi:water-percent
      battery_ignore: true
    sensor.pressure_office:
      friendly_name: Office Pressure
      icon: mdi:arrow-collapse-all
      battery_ignore: true
    sensor.temperature_office:
      friendly_name: Office Temperature
    switch.wall_switch_bathroom_left:
      friendly_name: Bathroom wall switch (L)
    switch.wall_switch_bathroom_right:
      friendly_name: Bathroom wall switch (R)

# vim: set filetype=yaml et sw=2 ts=2 :
