custom_updater:
  hide_sensor: true
  show_installable: false
  track:
    - components
    - cards
    - python_scripts
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
  component_urls:
    - https://raw.githubusercontent.com/robmarkcole/Hue-sensors-HASS/master/custom_updater.json
  # python_script_urls:
  #   -

# vim: set filetype=yaml et sw=2 ts=2 :
