custom_updater:
  show_installable: false
  hide_sensor: true
  track:
    - components
    - cards
    - python_scripts
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
  #   - https://raw.githubusercontent.com/awesome-developer/my-awesome-repo/master/custom_cards.json
  # component_urls:
  #   - https://raw.githubusercontent.com/awesome-developer/my-awesome-repo/master/custom_components.json

# vim: set filetype=yaml et sw=2 ts=2 :
