automation:
  - alias: HASS startup automation
    initial_state: true
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: shell_command.setup_routing
      - service: notify.html5
        data:
          message: "Home Assistant has (re)started"
          data:
            tag: "hass-restart"
            renotify: True
      - service: frontend.set_theme
        data:
          name: dark_theme
      # Request zanzito update
      - service: mqtt.publish
        data:
          topic: zanzito/ph1/cmd/send_heartbeat
          qos: 0
          retain: 0
      - delay: 00:05:00
      - service: script.enable_annoying_automations
      # Purge DB
      - delay: 00:10:00
      - service: recorder.purge

  - alias: Update notifications
    initial_state: true
    trigger:
      - platform: state
        entity_id: updater.updater
    action:
      service: notify.html5
      data_template:
        message: "Home Assistant {{ states.updater.updater.state }} is now available."


sensor:
  - platform: time_date

  - platform: uptime
    name: "Home Assistant Uptime"
    unit_of_measurement: minutes

  - platform: min_max
    name: 'Home Temperature'
    type: mean
    entity_ids:
      - sensor.hue_bathroom_temperature
      - sensor.hue_hallway_temperature
      - sensor.hue_kitchen_temperature
      - sensor.hue_toilet_temperature
      - sensor.temperature_living_room
      - sensor.temperature_bedroom
      - sensor.temperature_office
      # - sensor.pilea_temperature
      # - sensor.ficus_temperature


rest_command:
  ha_restart:
    method: get
    url: http://nasteanas.lan:8993/ha/restart


shell_command:
  setup_routing: !secret shell_cmd_setup_routing


script:
  ha_restart:
    alias: 'Restart HASS'
    sequence:
      - service: rest_command.ha_restart

  ha_reload_config:
    alias: 'Reload core config'
    sequence:
      - service: homeassistant.reload_core_config

  enable_annoying_automations:
    alias: 'Enable annoying automations'
    sequence:
      - service: automation.turn_on
        entity_id: automation.ask_to_buzz_door_open_when_approaching_home
      - service: automation.turn_on
        entity_id: automation.react_to_my_homecoming
      - service: automation.turn_on
        entity_id: automation.talk_to_my_wife_when_she_gets_home
      - service: automation.turn_on
        entity_id: automation.watching_teva
      - service: automation.turn_on
        entity_id: automation.playing_ps3


homeassistant:
  customize:
    # Entities belonging to HASS tab
    group.hass_infrastructure:
      order: 1
    group.zwave:
      order: 3
    # Master groups
    group.all:
      hidden: false
    group.all_automations:
      hidden: false
      order: 99
    group.all_covers:
      icon: mdi:window-open
      order: 2
      hidden: false
      friendly_name: All covers
    group.all_devices:
      icon: mdi:cellphone-android
      order: 2
      hidden: false
      friendly_name: All devices
    group.all_lights:
      hidden: false
      icon: mdi:lightbulb
      friendly_name: All lights
      order: 2
    group.all_scripts:
      control: hidden
      order: 1
      hidden: false
      friendly_name: All scripts
      icon: mdi:script
    group.all_switches:
      control: hidden
      hidden: false
      friendly_name: All switches
      order: 4
      icon: mdi:toggle-switch
    # Scripts
    script.ha_reload_config:
      icon: mdi:refresh
    script.ha_restart:
      icon: mdi:power

# vim: set filetype=yaml et sw=2 ts=2 :
