light:
  - platform: template
    lights:
      bathroom_ceiling:
        friendly_name: "Bathroom Ceiling"
        value_template: "{{ is_state('switch.shelly_bathroom_ceiling_light', 'on') }}"
        turn_on:
          service: switch.turn_on
          entity_id: switch.shelly_bathroom_ceiling_light
        turn_off:
          service: switch.turn_off
          entity_id: switch.shelly_bathroom_ceiling_light

  - platform: mqtt
    name: "Bathroom Ceiling MQTT"
    state_topic: 'shellies/shelly1-9F5CC0/relay/0'
    command_topic: 'shellies/shelly1-9F5CC0/relay/0/command'
    payload_on: 'on'
    payload_off: 'off'


switch:
  - platform: mqtt
    name: "Shelly Bathroom Ceiling Light"
    state_topic: 'shellies/shelly1-9F5CC0/relay/0'
    command_topic: 'shellies/shelly1-9F5CC0/relay/0/command'
    payload_on: "on"
    payload_off: "off"
    state_on: "on"
    state_off: "off"


automation:
  - alias: Sync state of bathroom ceiling light with bathroom light (ON)
    initial_state: true
    trigger:
      - platform: state
        entity_id: light.hue_bathroom
        to: 'on'
    action:
      service: light.turn_on
      entity_id: light.bathroom_ceiling

  - alias: Sync state of bathroom ceiling light with bathroom light (OFF)
    initial_state: true
    trigger:
      - platform: state
        entity_id: light.hue_bathroom
        to: 'off'
    action:
      service: light.turn_off
      entity_id: light.bathroom_ceiling


homeassistant:
  customize:
    light.bathroom_ceiling:
      icon: mdi:ceiling-light

# vim: set filetype=yaml et sw=2 ts=2 :
