light:
  - platform: mqtt
    name: "Bathroom Ceiling"
    state_topic: 'shellies/shelly1-9F5CC0/relay/0'
    command_topic: 'shellies/shelly1-9F5CC0/relay/0/command'
    payload_on: 'on'
    payload_off: 'off'


automation:
  - alias: Sync state of bathroom ceiling light with bathroom light (ON)
    initial_state: true
    trigger:
      - platform: state
        entity_id: light.hue_bathroom
        to: 'on'
    action:
      service: light.turn_on
      entity_id: light.bathroom_ceiling

  - alias: Sync state of bathroom ceiling light with bathroom light (OFF)
    initial_state: true
    trigger:
      - platform: state
        entity_id: light.hue_bathroom
        to: 'off'
    action:
      service: light.turn_off
      entity_id: light.bathroom_ceiling


homeassistant:
  customize:
    light.bathroom_ceiling:
      icon: mdi:ceiling-light

# vim: set filetype=yaml et sw=2 ts=2 :
