wemo:
  static:
    - wemo-insight-01.lan  # nasteanas
    - wemo-insight-02.lan  # washing machine


binary_sensor:
  - platform: template
    sensors:
      washing_machine:
        friendly_name: 'Washing Machine'
        delay_off:
          minutes: 2
        device_class: power
        value_template: '{{ states.switch.wemo_insight__washing_machine.attributes.state_detail == "on" }}'


sensor:
  - platform: template
    sensors:
      power_consumption_washing_machine:
        friendly_name: Washing Machine Power Consumption
        unit_of_measurement: W
        value_template: '{{ states.switch.wemo_insight__washing_machine.attributes.current_power_w }}'

  - platform: template
    sensors:
      power_consumption_nasteanas:
        friendly_name: NAS Power Consumption
        unit_of_measurement: W
        value_template: '{{ states.switch.wemo_insight__nasteanas.attributes.current_power_w }}'
        icon_template: mdi:flash


automation:
  - alias: Notify when the washing machine has finished
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.washing_machine
      from: "on"
      to: "off"
    action:
      - service: notify.html5
        data:
          message: "The Washing Machine has finished its cycle"
      - delay: '01:00:00'
      - service: script.turn_off_washing_maching_if_not_running

  - alias: "Turn washing machine wemo back on after 10 minutes of it being off"
    initial_state: true
    trigger:
      - platform: state
        entity_id: switch.wemo_insight__washing_machine
        to: 'off'
        for:
          minutes: 10
    action:
      service: switch.turn_on
      entity_id: switch.wemo_insight__washing_machine


script:
  turn_off_washing_maching_if_not_running:
    alias: 'Turn off washing if not running'
    sequence:
      - condition: state
        entity_id: binary_sensor.washing_machine
        state: "off"
      - service: switch.turn_off
        entity_id: switch.wemo_insight__washing_machine


homeassistant:
  customize:
    binary_sensor.washing_machine:
      icon: mdi:washing-machine
    switch.wemo_insight__nasteanas:
      icon: mdi:server-network
    switch.wemo_insight__washing_machine:
      icon: mdi:washing-machine

# vim: set filetype=yaml et sw=2 ts=2 :
