zone:
  - name: Work
    latitude: !secret work_latitude
    longitude: !secret work_longitude
    elevation: !secret work_elevation
    icon: mdi:worker


proximity:
  home:
    ignored_zones:
      - Work
    devices:
      - device_tracker.pschmitt_ph1
    tolerance: 10
    unit_of_measurement: m


sensor:
  - platform: google_travel_time
    name: Travel time to Home
    api_key: !secret google_maps_api_key
    origin: device_tracker.pschmitt_ph1
    destination: zone.home
    options:
      mode: walking

# vim: set filetype=yaml et sw=2 ts=2 :
