media_player:
  - platform: liveboxplaytv
    name: Livebox Play
    host: livebox-play.lan


binary_sensor:
  - platform: command_line
    name: Livebox Play TV
    device_class: power
    command: nmap -p 8080 -oG - --open livebox-play.lan 2>/dev/null | awk '!/^#/' | grep -q open && echo open || echo closed
    payload_on: open
    payload_off: closed


sensor:
  - platform: template
    sensors:
      tv_channel:
        value_template: '{{ states.media_player.livebox_play.attributes.source }}'
        friendly_name: 'Current TV Channel'


automation:
  - alias: Setup routing for livebox-play
    initial_state: true
    trigger:
      platform: homeassistant
      event: start
    action:
      service: shell_command.livebox_play_tv_setup_routing

  - alias: Daily reboot of the Livebox Play TV
    initial_state: true
    trigger:
      - platform: time_pattern
        hours: 4
        minutes: 35
        seconds: 12
    action:
      - service: script.reboot_livebox_play


shell_command:
  livebox_play_tv_setup_routing: !secret livebox_play_tv_setup_routing
  livebox_play_tv_turn_on: liveboxplaytv -H livebox-play.lan on
  livebox_play_tv_turn_off: liveboxplaytv -H livebox-play.lan off


script:
  turn_off_livebox_play_tv:
    alias: Turn off the livebox play
    sequence:
      - service: media_player.turn_off
        data:
          entity_id: media_player.livebox_play

  turn_on_livebox_play:
    alias: Force turning on the Livebox Play TV
    sequence:
      - service: media_player.turn_on
        data:
          entity_id: media_player.livebox_play

  livebox_play_tv_set_start_chanel:
    alias: "Set start channel on Livebox Play TV"
    sequence:
      - service: script.harmony_livebox_play_tv_send_return_key
      - service: media_player.select_source
        entity_id: media_player.livebox_play
        data_template:
          source: '{{ tv_channel|default("TF1") }}'

# vim: set filetype=yaml et sw=2 ts=2 :
